role: "Cloud Architect"
location: "Stockholm, Sweden"
focus: "architect"

summary_type: "architect_focused"
skills_profile: "architect_skills"

highlight_keywords:
  - "Azure Architecture"
  - "Cost Optimization"
  - "Cloud Strategy"
  - "Solution Design"
  - "Stakeholder Engagement"
  - "Governance"
  - "Infrastructure as Code"
  - "Enterprise Architecture"

experience_emphasis:
  - "architecture_bullets"
  - "cost_optimization_bullets"
  - "stakeholder_bullets"
  - "strategy_bullets"

soft_skills:
  - "Strategic thinking"
  - "Stakeholder management"
  - "Technical leadership"
  - "Architecture reviews"
